### ISSUE TITLE
好棒，org就剩下即时渲染数学公式的问题了

### ISSUE THREAD

**Issue by AbstProcDo** [casouri/iscroll#2]
org不适用于两种情况的阅读 ，一是大量的图片， 二是很多数学公式。
以上两种情况，只好用typora。

**Comment by casouri** [comment]
有不少包能实时渲染org里的latex公式，比如 https://github.com/yangsheng6810/org-latex-impatient 和 https://orgmode.org/manual/Previewing-LaTeX-fragments.html
