### ISSUE TITLE
Support pdf-tools?

### ISSUE THREAD

**Issue by seagle0128** [casouri/iscroll#4]
Since pdf-tools converts to image and display, is it possible to make iscroll support it?

**Comment by casouri** [comment]
I don't use pdf-tools. Does it not support scrolling? In vanilla Emacs, any image taller than the window should scroll fine without iscroll.el.

**Comment by seagle0128** [comment]
`pdf-tools` doesn't support continuous scrolling. When scrolling to the edge of the page, it jumps to the next page.

**Comment by casouri** [comment]
I see. If pdf-tools displays multiple pages in the same time, then iscroll can give you continuous scrolling; but if pdf-tools displays a single page at a time and only load a new page when you scroll to the bottom, iscroll can't help you. Does pdf-tools display multiple pages in the same time, or a single page at a time? If the former, does `iscroll-down` and `iscroll-up` work for you?

**Comment by seagle0128** [comment]
I think pdf-tools displays multiple pages. When I enable `iscroll-mode` with `pdf-view-mode`,  the next page is able to be display the half, and then jump to the next page.

**Comment by casouri** [comment]
Since Emacs has added pixel scrolling, I guess this is not a problem anymore ;-)

**Comment by seagle0128** [comment]
Well. I don't think the problem is understood. pixel scrolling won't address this issue. But I am closing it for now.

BTW,  there is some compatibility issues in pdf buffers if `pixel-scroll-precision-mode` is enabled. It will make the scrolling not working in pdf buffers.
