### ISSUE TITLE
GIF size in repo is too large

### ISSUE THREAD

**Issue by zealotrush** [casouri/iscroll#8]
The size of the `demo.gif` file in the repo is huge: 49 M.  This makes it difficult for me to clone the repo sometimes -- I'm in China and have really slow and unstable connection to GitHub.  It would be helpful to reduce the GIF to, say, 1 M, or move it outside of the repo.

And thanks for the great package.  I use it everyday and can't live without it.

**Comment by casouri** [comment]
Ok, done.
